"""Build the full key -> Thai file for the Solution 2 plugin.

    s2_kv.json           key   -> game text (zh-cn, from the AssetRipper dump)
    Translation ... .txt  zh-cn -> Thai      (the XUnity dictionary, 76k entries)
    ------------------------------------------------------------------------
    plugin Thai.tsv      key   -> Thai

No new translation work: this is a join. The dictionary already covers 97.95% of the
game's texts; what the join buys is that every KEY now carries its own value, so the
12,761 keys (17%) that share their text with another key can finally diverge.

Run:  python tools/solution2/s2_full.py [out.tsv]

⚠️ Join against s2_kv.json (zh-cn), NOT against the runtime dump — the live
LeanLocalization table is Traditional Chinese while the dictionary is keyed on Simplified.
The keys themselves are language-independent, so the injection is unaffected.
"""
import sys, io, json, re, os, collections

if __name__ == "__main__":   # re-wrapping on import would close the importer's stdout
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "tools", "v16"))
import xkey  # noqa: E402  correct unescaped-'=' split

DICT = os.path.join(ROOT, "Mod", "BepInEx", "Translation", "th", "Text", "Translation zh-CN to en.txt")
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "plugin", "LomThaiText", "full", "Thai.tsv")

BSN = "\\" + "n"
THAI = re.compile(r"[฀-๿]")
CMD = re.compile(r"\{/?(?:punch|vpunch|hpunch|flash|w|wi|wc|wvo|wp|c|x|s)(?:=[^}]*)?\}")


def to_dict_key(text):
    """Game text -> the exact key form our dictionary uses. (Same rules as tools/v16/v16_build.py)"""
    t = CMD.sub("", text)
    t = re.sub(r"\{(size|color|link)=([^}]*)\}", lambda m: "<" + m.group(1) + "\\=" + m.group(2) + ">", t)
    t = re.sub(r"\{/(size|color|link)\}", lambda m: "</" + m.group(1) + ">", t)
    t = t.replace("{b}", "<b>").replace("{/b}", "</b>").replace("{i}", "<i>").replace("{/i}", "</i>")
    t = t.replace(BSN, "")          # our dict stores multi-line keys with the newline removed
    t = t.strip()
    return re.sub(r"(?<!\\)=", "\\\\=", t)


FUNGUS_NS = ("Story/", "CombatTalking/")


def to_native(v, key=""):
    """Dictionary value -> the form the game itself uses.

    The dictionary keeps XUnity's escaped rich text, `<size\\=20>ไทย</size>`. Where that text
    goes decides how to write it back:
      • Story/ and CombatTalking/ run through Fungus, which wants `{size=20}ไทย{/size}`
      • everything else lands in a UGUI Text, which wants `<size=20>` — writing `{size=20}`
        there renders the braces literally (this is what put "{size=20}ชุมชนผู้เล่น…{/size}"
        on the title screen)
    A literal `\\n` is left alone — the plugin's loader turns it into a real newline."""
    v = v.replace("\\=", "=")
    if not key.startswith(FUNGUS_NS):
        return v
    v = re.sub(r"<(size|color|link)=([^>]*)>", lambda m: "{" + m.group(1) + "=" + m.group(2) + "}", v)
    v = re.sub(r"</(size|color|link)>", lambda m: "{/" + m.group(1) + "}", v)
    return (v.replace("<b>", "{b}").replace("</b>", "{/b}")
             .replace("<i>", "{i}").replace("</i>", "{/i}"))


def main():
    kv = json.load(open(os.path.join(HERE, "s2_kv.json"), encoding="utf-8"))
    d = xkey.load(DICT)
    print(f"game keys: {len(kv)}   dictionary entries: {len(d)}")

    out, c = {}, collections.Counter()
    misses = []
    for k, text in kv.items():
        if not text.strip():
            c["empty game text"] += 1
            continue
        dk = to_dict_key(text)
        if not dk:
            c["empty after tag strip"] += 1
            continue
        hit = d.get(dk)
        if hit is None:
            c["NO dictionary entry"] += 1
            if len(misses) < 40:
                misses.append((k, text[:60]))
            continue
        val = to_native(hit[1], k)
        if not THAI.search(val):
            c["entry exists but not Thai"] += 1
            continue
        if "\t" in val or "\n" in val or "\r" in val:
            val = val.replace("\r", "").replace("\n", BSN).replace("\t", "\\t")
            c["had a raw control char (escaped)"] += 1
        out[k] = val
        c["TRANSLATED"] += 1
        if BSN in text:
            c["  ...of which source had \\n"] += 1
            if BSN not in val:
                c["  ...and the line break was lost"] += 1

    for x, n in c.most_common():
        print(f"  {x:<36}{n:>7}")
    print(f"  {'coverage':<36}{c['TRANSLATED']*100.0/len(kv):>6.2f}%")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("# LoM Thai Text — full key->Thai table\n")
        f.write("# generated by tools/solution2/s2_full.py — do not hand-edit\n")
        f.write(f"# {c['TRANSLATED']} of {len(kv)} game keys\n")
        for k in sorted(out):
            f.write(k + "\t" + out[k] + "\n")
    print(f"\nwrote {OUT}  ({os.path.getsize(OUT)/1048576:.1f} MB)")

    if misses:
        print("\nsample keys with no dictionary entry:")
        for k, t in misses[:15]:
            print(f"  {k:<44}{t}")


if __name__ == "__main__":
    main()
