"""Merge the hand-written gap file over the joined table, verify, and install.

    python tools/solution2/s2_merge.py            # build + verify
    python tools/solution2/s2_merge.py --install  # ... and copy into the game
"""
import sys, io, os, json, re, shutil, collections

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

JOINED = os.path.join(ROOT, "plugin", "LomThaiText", "full", "Thai.tsv")
GAPS = os.path.join(HERE, "gaps_thai.tsv")
GAME = r"C:\Program Files (x86)\Steam\steamapps\common\LegendOfMortal\BepInEx\plugins\LomThaiText\Thai.tsv"

THAI = re.compile(r"[฀-๿]")
BSN = "\\" + "n"


def read(path):
    rows, bad = {}, []
    for i, line in enumerate(open(path, encoding="utf-8")):
        line = line.rstrip("\n")
        if not line or line.startswith("#"):
            continue
        if line.count("\t") != 1:
            bad.append((i + 1, line[:70]))
            continue
        k, v = line.split("\t")
        rows[k] = v
    return rows, bad


def main():
    joined, bad1 = read(JOINED)
    gaps, bad2 = read(GAPS)
    if bad1 or bad2:
        print("!! lines without exactly one TAB:", bad1[:5], bad2[:5])
        return 1
    print(f"joined: {len(joined)}   hand-written gaps: {len(gaps)}")

    kv = json.load(open(os.path.join(HERE, "s2_kv.json"), encoding="utf-8"))
    unknown = [k for k in gaps if k not in kv]
    if unknown:
        print(f"!! {len(unknown)} gap keys are not real game keys: {unknown[:8]}")
        return 1
    print(f"   overwrites from the gap file: {sum(1 for k in gaps if k in joined)}")

    merged = dict(joined)
    merged.update(gaps)

    # --- verification -----------------------------------------------------
    err = collections.Counter()
    for k, v in merged.items():
        if not v:
            err["empty value"] += 1
        if "\t" in v or "\n" in v or "\r" in v:
            err["raw control char"] += 1
        if not THAI.search(v) and not re.match(r"^[\s0-9{}\[\]$:.,%+\-]*$", v):
            err["no Thai and not numeric/format"] += 1
        # a value must not carry the XUnity dictionary escape into the game
        if "\\=" in v:
            err["leftover XUnity \\= escape"] += 1
        if "<size" in v or "</size>" in v:
            err["UGUI tag form left in a Fungus string"] += 1
    for x, n in err.most_common():
        print(f"  !! {x}: {n}")

    banned = collections.Counter()
    for v in merged.values():
        for w in ("ครับ", "ฉัน", "เธอ", "คุณ", "ผม", "ดิฉัน"):
            if w in v:
                banned[w] += 1
    print("  register check (expected 0 except the ผม/คุณ false positives):", dict(banned))

    out = os.path.join(ROOT, "plugin", "LomThaiText", "full", "Thai.merged.tsv")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"# LoM Thai Text — {len(merged)} keys "
                f"({len(joined)} joined from the dictionary + {len(gaps)} hand-written)\n")
        f.write("# generated by tools/solution2/s2_merge.py — do not hand-edit\n")
        for k in sorted(merged):
            f.write(k + "\t" + merged[k] + "\n")
    print(f"\nwrote {out}  ({os.path.getsize(out)/1048576:.1f} MB, {len(merged)} keys, "
          f"{len(merged)*100.0/len(kv):.2f}% of the game's {len(kv)} keys)")

    if "--install" in sys.argv:
        shutil.copyfile(out, GAME)
        print("installed -> " + GAME)
    return 0


if __name__ == "__main__":
    sys.exit(main())
